#Use the official AWS lambda python 3,12 image
FROM python:3.12

#Install the minimal dependencies using available tools
WORKDIR ${LAMBDA_TASK_ROOT}

# Copy the requirements file into the image
COPY requirements.txt .

#install the dependencies using openai>=1.10.0
RUN pip install --no-cache-dir pillow boto3 openai>=1.10.0

#Install the rest of the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy function code
COPY lambda_function.py .
COPY images/ .

#Set the CMD to your handler
CMD ["lambda_function.lambda_function_handler"]
